name: Deploy to Development App

on:
  push:
    branches:
      - default

env:
  YARN_CACHE_FOLDER: .cache/yarn
  npm_config_cache: .cache/npm

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      # https://blog.lacolaco.net/2021/06/github-actions-yarn-cache/
      - name: Cache npm cache
        uses: actions/cache@v2
        with:
          path: ${npm_config_cache}
          key: ${{ runner.os }}-npm-cache-v1

      - name: Install essensial tools
        run: |
          npm install -g yarn firebase-tools

      - name: Cache yarn cache
        uses: actions/cache@v2
        with:
          path: ${YARN_CACHE_FOLDER}
          key: ${{ runner.os }}-yarn-cache-v1

      - name: Build `nuxt` app
        run: |
          yarn install --frozen-lockfile
          yarn nuxt build --standalone
          yarn build:copy:server -v
          yarn build:copy:client -v
        env:
          APP_ENV: development
        working-directory: ./nuxt

      - name: Build the server-side functions
        run: npm ci
        working-directory: ./functions

      - name: Deploy (Cloud Functions & Hosting)
        run: |
          firebase use default
          firebase deploy --only functions,hosting --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
